import images from "../../assets/images";

export const DATA: any = [
    { image: images.buildings },
    { image: images.buildings },
    { image: images.buildings },
    { image: images.buildings },
    { image: images.buildings },
    { image: images.buildings },
    { image: images.buildings },
    { image: images.buildings },
    { image: images.buildings },
    { image: images.buildings },
    { image: images.buildings },
    { image: images.buildings },
    { image: images.buildings },
    { image: images.buildings },
    { image: images.buildings },
    { image: images.buildings },
    { image: images.buildings },
    { image: images.buildings },
    { image: images.buildings },
    { image: images.buildings },
    { image: images.buildings },
  ];