import LocalizedStrings from 'react-native-localization';

const strings = new LocalizedStrings({
  en: {
    signInText: 'SIGN IN',
    justo: 'Justo',
    notificationHeader: 'Notification',
    dashboardHeader: 'Dashboard',
    registrationHeader: 'Registration',
    companyDetails: 'Company Information',
    registernow: 'register now',
    propertyHeader: 'Property',
    propertyManagementHeader: 'Property Management',
    agencyHeader: 'Agent',
    leadManagementHeader: 'Lead Management',
    appointmentWithCPHeader: 'Appointment With CP',
    appointmentForVisitHeader: 'Appointment For Site Visit',
    reportHeader: 'Report',
    chatHeader: 'Chat',
    supportHeader: 'Support',
    settingHeader: 'Setting',
    logout: 'LogOut',
    versionText: 'version',
    forgotPassword: 'Forgot Password?',
    newUserText: 'New User?',
    signUp: 'Sign Up',
    byCreating: 'By Signing up you agree to our',
    termsAndCondition: 'Terms & Conditions',
    and: 'and',
    privacyPolicy: 'Privacy Policy',
    ofJusto: 'of Justo.',
    basicInfoText: 'Basic Information',
    allocate: 'Allocate',
    propertyDetailHeader: 'Property Detail',
    searchProperty: 'Search Property',
    resend: 'Resend',
    notRecived: `Didn't receive the code?`,
    codeSent: 'A verification code has been sent to',
    your: ' your',
    email: 'email address',
    otpVerification: 'OTP VERIFICATION',
    imagecontentHeader: 'Images',
    videocontentHeader: 'Videos',
    cataloguecontentHeader: 'Catalogue',
    createVisit: 'CREATE VISIT',
    gender: "Gender :",
    male: "Male",
    female: "Female",
    next: 'next',
    addnewagent: 'Add new Agent',
    agentdetail: 'Agent Detail',
    logInText: 'LOG IN',
    dontHaveAnAcc: `Don't Have an account?`,
    registerNow: 'Register Now',

    /**Confirm Model**/
    ConfirmationModalTxt: 'Select the reason for\r\nunsubscribe this property.',
    Confirm: 'Confirm',
    
    
    /*** agency ***/
    addnewAgency: 'Add new Agency',
    pendingconfirm: 'Pending Confirm',
    edit: 'Edit',
    deactive: 'Deactive',
    Agencydetail: 'Agency Detail',
    userbankinfo: 'User Bank Info',
    createnewagency: 'Create New Agency',
    confirmation: 'Confirmation',
    active:'Active',
    searchAgency:'Search Agency',
    apply:'Apply',
    no: 'No', 
    yes: 'Yes', 
    agent: 'Agent', 
    createAgent: 'Create Agent', 
    updatepassword: 'Update Password',
    deactivconfirmation: 'Are You sure you want to Deactive this',

    // All Leads
    visitor: 'Visitor',
    bulkupload: 'Bulk Upload',
    uploadCSV: 'Upload CSV',
    uploadimage: 'Upload Image',
    addnewvisitor: 'Add New Visitor',
    editVisitor: 'Update Visitor',
    visitordetails: 'Visitor Details',
    searchvisitor: 'Search Visitor',
    propertyrequire: 'Property Require',
    createVisitor: 'Create Visitor',
    Statusupdate: 'Status Update',
    ScheduleSitevisite: 'Schedule Site Visite',
  },
});

export default strings;
